name: AstrBot
services:
  astrbot:
    build:
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:6518
        - HTTPS_PROXY=http://host.docker.internal:6518
    # image: soulter/astrbot:latest
    container_name: astrbot
    restart: always
    command: >
      sh -c "
        # 安装npm
        apt update && apt install -y npm &&
        # 这里可以添加其他需要自动执行的命令
        # cd /App/dashboard && npm install &&
        # 最后保留tail命令保持容器运行
        tail -f /dev/null
      "
    security_opt:
      - no-new-privileges:true
    ports:
      - "6185:6185" # AstrBot WebUI
      - "6199:6199" # Optional. OneBot v11 Napcat Websocket Port
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ..:/App
      # - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro