name: AstrBot
services:
  astrbot:
    build:
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:6518
        - HTTPS_PROXY=http://host.docker.internal:6518
    # image: soulter/astrbot:latest
    container_name: astrbot
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "6185:6185" # AstrBot WebUI
      - "6199:6199" # Optional. OneBot v11 Napcat Websocket Port
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ..:/App
      # - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:16-alpine
    container_name: astrbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: astrbot
      POSTGRES_PASSWORD: astrbot123
      POSTGRES_DB: astrbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
